<template>
  <div class="bg-blue-500">Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum nesciunt in magnam neque excepturi eveniet minus. Eligendi repellendus adipisci aperiam dolore magnam atque, veritatis aliquam veniam inventore dicta fugit ducimus, necessitatibus dolorum quibusdam ullam quod autem suscipit incidunt! Perspiciatis unde dolores fugit optio harum iure pariatur dolorem iusto architecto? Vero, enim voluptas vitae repudiandae voluptates praesentium. Porro, perspiciatis aliquam ad asperiores quisquam aperiam molestiae aliquid perferendis sed optio autem consequuntur inventore, atque dicta similique. Commodi neque modi non quae fugit amet, ad aliquid nisi ipsam, blanditiis explicabo deleniti. Iste reiciendis quidem tenetur velit natus temporibus odit accusantium soluta incidunt et sunt vel perferendis quia in quo dignissimos repellendus libero at quam nulla, ipsa fugit atque enim. Sint eos eaque suscipit quaerat ab beatae facere perferendis tenetur sequi enim unde voluptatum, fugiat temporibus ratione saepe ipsum quam. Possimus rem aliquid sequi perferendis accusamus aperiam beatae dolor impedit necessitatibus iste animi accusantium excepturi sapiente quam perspiciatis esse vitae, fuga cumque deleniti ipsa suscipit quos velit officiis molestias? Reprehenderit voluptate, officiis harum doloribus tempore totam, recusandae ducimus dolores dolorum, autem velit iusto nemo ullam? Blanditiis ex perferendis accusamus velit. Obcaecati dolorum voluptas cumque veritatis minus soluta provident odio quam sit itaque, consectetur laudantium nobis hic ratione illo exercitationem voluptatem rerum dolor impedit eaque eos nihil tempora? Facilis deserunt vel architecto sint optio doloremque porro corrupti qui, consequatur reiciendis incidunt impedit rem, voluptatibus, delectus doloribus sit maiores omnis id. Maiores voluptates minima mollitia animi aperiam, quisquam modi totam quidem nihil consectetur laudantium! Suscipit, debitis corrupti qui velit mollitia culpa rerum facilis, veritatis delectus tenetur placeat asperiores incidunt deserunt unde? Dicta dignissimos, officia odit nisi maxime nulla facilis itaque natus dolorum porro necessitatibus pariatur quod ducimus quisquam praesentium, ut autem eveniet fugit ipsam amet perferendis? Facere commodi ullam praesentium reprehenderit et numquam repudiandae recusandae aliquid?</div>
</template>

<script>
export default {

}
</script>

<style>

</style>